---
title: "final_model2"
author: "Helen Evangelina"
date: "22/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(xaringanthemer)
library(kableExtra)
library(patchwork)
library(tmap)
library(knitr)
library(kableExtra)
library(tidymodels)
library(GGally)
library(ranger)
library(lime)
library(raster)
library(gridExtra)
library(tmap)
library(lubridate)
library(plotly)
```

```{r}
data <- read.csv(here::here("VICfire/data/model_df2.csv")) %>% na.omit() %>%
  dplyr::select(-year)
model <- readRDS(here::here("VICfire/model/rfmodel_final.rds"))
```


```{r}
data_predict <- data %>% select(-fire_count)
predicted <- predict(model, data_predict)$predictions

predicted_data <- tibble(pred = predicted) %>%
  bind_cols(data)
data_oct <- data %>% filter(month == 10) %>%
  ungroup() %>%
  dplyr::select(x,y,fire_count)
coordinates(data_oct) = c("x", "y")
data_oct_raster <- rasterFromXYZ(data_oct)
data_actual_oct <- tm_shape(data_oct_raster) +
  tm_raster(style = "cont", 
            palette = "seq",
                  alpha = 0.4) +
  tm_shape(vic_map_sf) +
  tmap::tm_borders(lwd = 3) +
  tm_layout(title = "October")
# pred data
data_oct_pred <- predicted_data %>%
  filter(month == 10) %>%
  dplyr::select(x,y,pred)

coordinates(data_oct_pred) = c("x", "y")
pred_oct_data_raster <- rasterFromXYZ(data_oct_pred)
data_pred_oct <- tm_shape(pred_oct_data_raster) +
  tm_raster(style = "cont", 
            palette = "seq",
                  alpha = 0.4) +
  tm_shape(vic_map_sf) +
  tmap::tm_borders(lwd = 3)
# for nov
data_nov <- data %>% filter(month == 11) %>%
  ungroup() %>%
  dplyr::select(x,y,fire_count)
coordinates(data_nov) = c("x", "y")
data_nov_raster <- rasterFromXYZ(data_nov)
data_actual_nov <- tm_shape(data_nov_raster) +
  tm_raster(style = "cont", 
            palette = "seq",
                  alpha = 0.4) +
  tm_shape(vic_map_sf) +
  tmap::tm_borders(lwd = 3) +
  tm_layout(title = "November")
# pred data
data_nov_pred <- predicted_data %>%
  filter(month == 11) %>%
  dplyr::select(x,y,pred)
coordinates(data_nov_pred) = c("x", "y")
pred_nov_data_raster <- rasterFromXYZ(data_nov_pred)
data_pred_nov <- tm_shape(pred_nov_data_raster) +
  tm_raster(style = "cont", 
            palette = "seq",
                  alpha = 0.4) +
  tm_shape(vic_map_sf) +
  tmap::tm_borders(lwd = 3)
# for dec
data_dec <- data %>% filter(month == 12) %>%
  ungroup() %>%
  dplyr::select(x,y,fire_count)
coordinates(data_dec) = c("x", "y")
data_dec_raster <- rasterFromXYZ(data_dec)
data_actual_dec <- tm_shape(data_dec_raster) +
  tm_raster(style = "cont", 
            palette = "seq",
                  alpha = 0.4) +
  tm_shape(vic_map_sf) +
  tmap::tm_borders(lwd = 3) +
  tm_layout(title = "December")
# pred data
data_dec_pred <- predicted_data %>%
  filter(month == 12) %>%
  dplyr::select(x,y,pred)
coordinates(data_dec_pred) = c("x", "y")
pred_dec_data_raster <- rasterFromXYZ(data_dec_pred)
data_pred_dec <- tm_shape(pred_dec_data_raster) +
  tm_raster(style = "cont", 
            palette = "seq",
                  alpha = 0.4) +
  tm_shape(vic_map_sf) +
  tmap::tm_borders(lwd = 3)
# for jan
data_jan <- data %>% filter(month == 1) %>%
  ungroup() %>%
  dplyr::select(x,y,fire_count)
coordinates(data_jan) = c("x", "y")
data_jan_raster <- rasterFromXYZ(data_jan)
data_actual_jan <- tm_shape(data_jan_raster) +
  tm_raster(style = "cont", 
            palette = "seq",
                  alpha = 0.4) +
  tm_shape(vic_map_sf) +
  tmap::tm_borders(lwd = 3) +
  tm_layout(title = "January")
# pred data
data_jan_pred <- predicted_data %>%
  filter(month == 1) %>%
  dplyr::select(x,y,pred)
coordinates(data_jan_pred) = c("x", "y")
pred_jan_data_raster <- rasterFromXYZ(data_jan_pred)
data_pred_jan <- tm_shape(pred_jan_data_raster) +
  tm_raster(style = "cont", 
            palette = "seq",
                  alpha = 0.4) +
  tm_shape(vic_map_sf) +
  tmap::tm_borders(lwd = 3)
# for feb
data_feb <- data %>% filter(month ==2) %>%
  ungroup() %>%
  dplyr::select(x,y,fire_count)
coordinates(data_feb) = c("x", "y")
data_feb_raster <- rasterFromXYZ(data_feb)
data_actual_feb <- tm_shape(data_feb_raster) +
  tm_raster(style = "cont", 
            palette = "seq",
                  alpha = 0.4) +
  tm_shape(vic_map_sf) +
  tmap::tm_borders(lwd = 3) +
  tm_layout(title = "February")
# pred data
data_feb_pred <- predicted_data %>%
  filter(month == 2) %>%
  dplyr::select(x,y,pred)
coordinates(data_feb_pred) = c("x", "y")
pred_feb_data_raster <- rasterFromXYZ(data_feb_pred)
data_pred_feb <- tm_shape(pred_feb_data_raster) +
  tm_raster(style = "cont", 
            palette = "seq",
                  alpha = 0.4) +
  tm_shape(vic_map_sf) +
  tmap::tm_borders(lwd = 3)
# for march
data_mar <- data %>% filter(month == 3) %>%
  ungroup() %>%
  dplyr::select(x,y,fire_count)
coordinates(data_mar) = c("x", "y")
data_mar_raster <- rasterFromXYZ(data_mar)
data_actual_mar <- tm_shape(data_mar_raster) +
  tm_raster(style = "cont", 
            palette = "seq",
                  alpha = 0.4) +
  tm_shape(vic_map_sf) +
  tmap::tm_borders(lwd = 3) +
  tm_layout(title = "March")
# pred data
data_mar_pred <- predicted_data %>%
  filter(month == 3) %>%
  dplyr::select(x,y,pred)
coordinates(data_mar_pred) = c("x", "y")
pred_mar_data_raster <- rasterFromXYZ(data_mar_pred)
data_pred_mar <- tm_shape(pred_mar_data_raster) +
  tm_raster(style = "cont", 
            palette = "seq",
                  alpha = 0.4) +
  tm_shape(vic_map_sf) +
  tmap::tm_borders(lwd = 3)
```

```{r map-rf-test2,warning = FALSE, message = FALSE}
tmap_arrange( data_actual_oct, data_pred_oct,
              data_actual_nov, data_pred_nov,
              data_actual_dec, data_pred_dec,
              data_actual_jan, data_pred_jan,
              data_actual_feb, data_pred_feb,
              data_actual_mar, data_pred_mar)
```
