---
title: "model"
author: "Helen Evangelina"
date: "25/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ranger)
```

```{r}
#reading data
data <- read.csv(here::here("VICfire/data/model_df2.csv"))

data <- data %>% mutate(id = as.factor(id))
```

```{r}
data_final <- data %>% 
  na.omit() %>% 
  dplyr::select(-year) %>% mutate(month = as.factor(month))

set.seed(2021)
randomforest_final <- ranger(fire_count ~ .-id, data = data_final, importance = "impurity")
randomforest_final
```

```{r test-summary}
test2 <- test %>%
  left_join(lonlat, by = "id") %>%
  dplyr::select(-id, -year) %>%
  mutate(month = as.factor(month))

predicted <- predict(randomforest_final, test2)$predictions

# Function for evaluating model
model_summary <- function(truth, estimate){
  
  df_new <- data.frame(truth = truth,
                       estimate = estimate)
  
  data.frame(RMSE = rmse_vec(truth, estimate),
             MAE = mae_vec(truth, estimate),
             "R-Square" = rsq_vec(truth, estimate),
             check.names = F
             ) %>% 
    mutate(MSE = mean((truth - estimate)^2))
}

kable(model_summary(truth = test2$fire_count,
           estimate = predicted))
```

```{r}
saveRDS(randomforest_final, "rfmodel_final.rds")
```