---
title: "heatmaps2"
author: "Helen Evangelina"
date: "18/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
model2 <- readRDS(here::here("VICfire/model/rfmodel2.rds"))
```

```{r}
load(here::here("VICfire/data/ida_report.Rdata"))

data <- train %>%
  bind_rows(test)

forest <- data %>% select(id, forest) %>%
  mutate(id = as.numeric(id))

forest <- forest[!duplicated(forest[,c('id')]),]
```

```{r}
# creating a raster for victoria
vic_raster <- raster(
  # no. of rows & columns (directly linked to resolution of grid cell)
  nrows = 20,
  ncols = 20,
  
  # bbox (bounding box of Victoria)
  xmn = 140.9617,
  xmx = 149.9763,
  ymn = -39.13396,
  ymx = -33.99605,
  
  # crs
  crs = "+proj=longlat +datum=WGS84"
  )
vic_raster[] <- 1:ncell(vic_raster)

# creating the lon & lat for each cell id
lonlat <- as.data.frame(coordinates(vic_raster)) %>%
  mutate(id = 1:400) %>%
  mutate(row = (id-1)%/%20 + 1, 
         col = (id-1)%%20 + 1)

data <- data %>% 
  mutate(id = as.numeric(id)) %>%
  left_join(lonlat, by = "id")
```

```{r}
data_avg <- data %>%
  select(-year, fire_count, - forest) %>%
  group_by(id, month) %>%
  summarise_all("mean") %>%
  left_join(forest, by = "id") %>%
  ungroup() %>%
  select(-id, -col, -row)
```

# predictions based on avg values of the data
```{r}
predicted <- predict(model2, data_avg)$predictions

predicted_data <- data_avg %>% bind_cols(predicted = predicted) %>%
  select(x, y, month, predicted) %>%
  left_join(lonlat, by = c("x", "y"))
```

```{r}
ggplot(predicted_data) +
  geom_tile(aes(y = row, 
                x = col, 
                fill = predicted)) +
  scale_fill_distiller(palette = "YlOrBr", direction = 1) + 
  theme_void() +
  facet_wrap(~month,
             ncol =3)
```
# oct
```{r}
oct_plot <- predicted_data %>%
  filter(month == 10) %>%
  ggplot() +
  geom_tile(aes(y = row, 
                x = col, 
                fill = predicted)) +
  scale_fill_distiller(palette = "YlOrBr", direction = 1) + 
  theme_void()
```

# nov
```{r}
nov_plot <- predicted_data %>%
  filter(month == 11) %>%
  ggplot() +
  geom_tile(aes(y = row, 
                x = col, 
                fill = predicted)) +
  scale_fill_distiller(palette = "YlOrBr", direction = 1) + 
  theme_void()
```

# dec
```{r}
dec_plot <- predicted_data %>%
  filter(month == 12) %>%
  ggplot() +
  geom_tile(aes(y = row, 
                x = col, 
                fill = predicted)) +
  scale_fill_distiller(palette = "YlOrBr", direction = 1) + 
  theme_void()
```

#jan
```{r}
jan_plot <- predicted_data %>%
  filter(month == 1) %>%
  ggplot() +
  geom_tile(aes(y = row, 
                x = col, 
                fill = predicted)) +
  scale_fill_distiller(palette = "YlOrBr", direction = 1) + 
  theme_void()
```

# feb
```{r}
feb_plot <- predicted_data %>%
  filter(month == 2) %>%
  ggplot() +
  geom_tile(aes(y = row, 
                x = col, 
                fill = predicted)) +
  scale_fill_distiller(palette = "YlOrBr", direction = 1) + 
  theme_void()
```

# mar
```{r}
mar_plot <- predicted_data %>%
  filter(month == 3) %>%
  ggplot() +
  geom_tile(aes(y = row, 
                x = col, 
                fill = predicted)) +
  scale_fill_distiller(palette = "YlOrBr", direction = 1) + 
  theme_void()
```

# max_temp
```{r}
min(data$max_temp)
max(data$max_temp)
```
14.8-37.8

## oct
```{r}
data_oct <- data_avg %>% filter(month == 10) %>%
  select(-fire_count)
data_oct_changed <- data.frame()
for (i in 14:38){
  temp <- data_oct %>% mutate(max_temp = i)
  data_oct_changed <- data_oct_changed %>% bind_rows(temp)
}

predicted_oct_temp <- predict(model2, data_oct_changed)$predictions

predicted_data_oct_temp <- data_oct_changed %>% bind_cols(predicted = predicted_oct_temp) %>%
    select(x, y, max_temp, predicted) %>%
    left_join(lonlat, by = c("x", "y"))
  
plot_oct_temp <- ggplot(predicted_data_oct_temp) +
  geom_tile(aes(y = row, 
                x = col, 
                fill = predicted)) +
  scale_fill_distiller(palette = "YlOrBr", direction = 1) + 
  theme_void() +
  facet_wrap(~max_temp, ncol = 5)
plot_oct_temp
```

## nov
```{r}
data_nov <- data_avg %>% filter(month == 11) %>%
  select(-fire_count)
data_nov_changed <- data.frame()
for (i in 14:38){
  temp <- data_nov %>% mutate(max_temp = i)
  data_nov_changed <- data_nov_changed %>% bind_rows(temp)
}

predicted_nov_temp <- predict(model2, data_nov_changed)$predictions

predicted_data_nov_temp <- data_nov_changed %>% bind_cols(predicted = predicted_nov_temp) %>%
    select(x, y, max_temp, predicted) %>%
    left_join(lonlat, by = c("x", "y"))
  
plot_nov_temp <- ggplot(predicted_data_nov_temp) +
  geom_tile(aes(y = row, 
                x = col, 
                fill = predicted)) +
  scale_fill_distiller(palette = "YlOrBr", direction = 1) + 
  theme_void() +
  facet_wrap(~max_temp, ncol = 5)
plot_nov_temp
```

## dec
```{r}
data_dec <- data_avg %>% filter(month == 12) %>%
  select(-fire_count)
data_dec_changed <- data.frame()
for (i in 14:38){
  temp <- data_dec %>% mutate(max_temp = i)
  data_dec_changed <- data_dec_changed %>% bind_rows(temp)
}

predicted_dec_temp <- predict(model2, data_dec_changed)$predictions

predicted_data_dec_temp <- data_dec_changed %>% bind_cols(predicted = predicted_dec_temp) %>%
    select(x, y, max_temp, predicted) %>%
    left_join(lonlat, by = c("x", "y"))
  
plot_dec_temp <- ggplot(predicted_data_dec_temp) +
  geom_tile(aes(y = row, 
                x = col, 
                fill = predicted)) +
  scale_fill_distiller(palette = "YlOrBr", direction = 1) + 
  theme_void() +
  facet_wrap(~max_temp, ncol = 5)
plot_dec_temp
```

## jan
```{r}
data_jan <- data_avg %>% filter(month == 1) %>%
  select(-fire_count)
data_jan_changed <- data.frame()
for (i in 14:38){
  temp <- data_jan %>% mutate(max_temp = i)
  data_jan_changed <- data_jan_changed %>% bind_rows(temp)
}

predicted_jan_temp <- predict(model2, data_jan_changed)$predictions

predicted_data_jan_temp <- data_jan_changed %>% bind_cols(predicted = predicted_jan_temp) %>%
    select(x, y, max_temp, predicted) %>%
    left_join(lonlat, by = c("x", "y"))
  
plot_jan_temp <- ggplot(predicted_data_jan_temp) +
  geom_tile(aes(y = row, 
                x = col, 
                fill = predicted)) +
  scale_fill_distiller(palette = "YlOrBr", direction = 1) + 
  theme_void() +
  facet_wrap(~max_temp, ncol = 5)
plot_jan_temp
```

- checking:
```{r}
predicted_data_jan_temp %>%
  filter(id == 61) %>%
  ggplot(aes(x = max_temp, 
             y = predicted)) +
  geom_line()
```

```{r}
predicted_data_jan_temp %>%
  filter(id == 272) %>%
  ggplot(aes(x = max_temp, 
             y = predicted)) +
  geom_line()
```

max_temp for 272 in the training set is 28

## feb
```{r}
data_feb <- data_avg %>% filter(month == 2) %>%
  select(-fire_count)
data_feb_changed <- data.frame()
for (i in 14:38){
  temp <- data_feb %>% mutate(max_temp = i)
  data_feb_changed <- data_feb_changed %>% bind_rows(temp)
}

predicted_feb_temp <- predict(model, data_feb_changed)$predictions

predicted_data_feb_temp <- data_feb_changed %>% bind_cols(predicted = predicted_feb_temp) %>%
    select(x, y, max_temp, predicted) %>%
    left_join(lonlat, by = c("x", "y"))
  
plot_feb_temp <- ggplot(predicted_data_feb_temp) +
  geom_tile(aes(y = row, 
                x = col, 
                fill = predicted)) +
  scale_fill_distiller(palette = "YlOrBr", direction = 1) + 
  theme_void() +
  facet_wrap(~max_temp, ncol = 5)
plot_feb_temp
```

## mar
```{r}
data_mar <- data_avg %>% filter(month == 3) %>%
  select(-fire_count)
data_mar_changed <- data.frame()
for (i in 14:38){
  temp <- data_mar %>% mutate(max_temp = i)
  data_mar_changed <- data_mar_changed %>% bind_rows(temp)
}

predicted_mar_temp <- predict(model, data_mar_changed)$predictions

predicted_data_mar_temp <- data_mar_changed %>% bind_cols(predicted = predicted_mar_temp) %>%
    select(x, y, max_temp, predicted) %>%
    left_join(lonlat, by = c("x", "y"))
  
plot_mar_temp <- ggplot(predicted_data_mar_temp) +
  geom_tile(aes(y = row, 
                x = col, 
                fill = predicted)) +
  scale_fill_distiller(palette = "YlOrBr", direction = 1) + 
  theme_void() +
  facet_wrap(~max_temp, ncol = 5)
plot_mar_temp
```