---
title: "plots"
author: "Helen Evangelina"
date: "22/11/2021"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ranger)
load(here::here("eda.RData"))
load(here::here("ida.RData"))
```

```{r}
model <- readRDS("rfmodel_final.rds")

data <- read.csv("model_df2.csv") %>%
  na.omit()
```

```{r}
# --- get mean and sd; for each variable
data_sd <- model_df2 %>% 
  na.omit() %>% 
  group_by(id) %>% 
  summarise(across(.cols = c(daily_rain:s0_pct_2, -forest),
                   .fns = list(mean = mean,
                               sd = sd),
                   .names = "{.col}_{.fn}"))

data_sd <- data_sd %>% mutate(id = as.numeric(id))
data_sd
data
```

```{r}
std_score <- tibble(sd = seq(-10, 10, by = 0.1),
                    percentage = seq(-100, 100, by = 1))
```


```{r}
id_list <- unique(data$id)
id_list
```

## max_temp
```{r}
data_avg <- data %>% 
  dplyr::select(-year) %>%
  group_by(id, month) %>%
  summarise_all("mean")

combined_data <- data.frame()
for (i in 1:length(id_list)) {
  id = id_list[i]
  data_id <- data_avg %>% filter(id == id_list[i])
  mean <- (data_sd %>% filter(id == id_list[i]))$max_temp_mean
  sd <- (data_sd %>% filter(id == id_list[i]))$max_temp_sd
  changed_data <- data.frame()
  for (j in -5:5) {
    new_values <- (j * sd) + mean
    data_id$max_temp <- new_values
    data_id <- data_id %>% filter(max_temp > 0)
    predicted_values <- mean(predict(model, data_id)$predictions)
    
    new_data <-tibble(id = id_list[i],
                      sd = j,
                      predict = predicted_values)
    
    changed_data <- changed_data %>% bind_rows(new_data)
  }
  combined_data <- combined_data %>% rbind(changed_data)
}

library(plotly)
combined_data %>% 
  group_by(id) %>%
  ggplot(aes(x = sd,
             y = predict,
             color = id,
             group = id)) +
  geom_point() + geom_line()
ggplotly()
```


## radiation
```{r}
combined_data2 <- data.frame()
for (i in 1:length(id_list)) {
  id = id_list[i]
  data_id <- data_avg %>% filter(id == id_list[i])
  mean <- (data_sd %>% filter(id == id_list[i]))$radiation_mean
  sd <- (data_sd %>% filter(id == id_list[i]))$radiation_sd
  changed_data <- data.frame()
  for (j in -5:5) {
    new_values <- (j * sd) + mean
    data_id$radiation <- new_values
    data_id <- data_id %>% filter(radiation > 0)
    predicted_values <- mean(predict(model, data_id)$predictions)
    
    new_data <-tibble(id = id_list[i],
                      sd = j,
                      predict = predicted_values)
    
    changed_data <- changed_data %>% bind_rows(new_data)
  }
  combined_data2 <- combined_data2 %>% rbind(changed_data)
}

combined_data2 %>% 
  group_by(id) %>%
  ggplot(aes(x = sd,
             y = predict,
             color = id,
             group = id)) +
  geom_point() + geom_line()
ggplotly()
```


## rh
```{r}
combined_data3 <- data.frame()
for (i in 1:length(id_list)) {
  id = id_list[i]
  data_id <- data_avg %>% filter(id == id_list[i])
  mean <- (data_sd %>% filter(id == id_list[i]))$rh_mean
  sd <- (data_sd %>% filter(id == id_list[i]))$rh_sd
  changed_data <- data.frame()
  for (j in -5:5) {
    new_values <- (j * sd) + mean
    data_id$rh <- new_values
    data_id <- data_id %>% filter(rh > 0)
    predicted_values <- mean(predict(model, data_id)$predictions)
    
    new_data <-tibble(id = id_list[i],
                      sd = j,
                      predict = predicted_values)
    
    changed_data <- changed_data %>% bind_rows(new_data)
  }
  combined_data3 <- combined_data3 %>% rbind(changed_data)
}

combined_data3 %>% 
  group_by(id) %>%
  ggplot(aes(x = sd,
             y = predict,
             color = id,
             group = id)) +
  geom_point() + geom_line()
ggplotly()
```

```{r}
save(data_sd, file = "data_sd.RData")
```


## daily_rain
```{r}
combined_data4 <- data.frame()
for (i in 1:length(id_list)) {
  id = id_list[i]
  data_id <- data_avg %>% filter(id == id_list[i])
  mean <- (data_sd %>% filter(id == id_list[i]))$daily_rain_mean
  sd <- (data_sd %>% filter(id == id_list[i]))$daily_rain_sd
  changed_data <- data.frame()
  for (j in -5:5) {
    new_values <- (j * sd) + mean
    data_id$daily_rain <- new_values
    
    predicted_values <- mean(predict(model, data_id)$predictions)
    
    new_data <-tibble(id = id_list[i],
                      sd = j,
                      predict = predicted_values,
                      daily_rain = new_values)
    
    changed_data <- changed_data %>% bind_rows(new_data)
  }
  combined_data4 <- combined_data4 %>% rbind(changed_data)
}

combined_data4 %>% 
  filter(daily_rain >0) %>%
  group_by(id) %>%
  ggplot(aes(x = sd,
             y = predict,
             color = id,
             group = id)) +
  geom_point() + geom_line()
ggplotly()
```

```{r}
length(data)
```


## et_short_crop
```{r}
combined_data5 <- data.frame()
for (i in 1:length(id_list)) {
  id = id_list[i]
  data_id <- data_avg %>% filter(id == id_list[i])
  mean <- (data_sd %>% filter(id == id_list[i]))$et_short_crop_mean
  sd <- (data_sd %>% filter(id == id_list[i]))$et_short_crop_sd
  changed_data <- data.frame()
  for (j in -5:5) {
    new_values <- (j * sd) + mean
    data_id$et_short_crop <- new_values
    predicted_values <- mean(predict(model, data_id)$predictions)
    
    new_data <-tibble(id = id_list[i],
                      sd = j,
                      predict = predicted_values)
    
    changed_data <- changed_data %>% bind_rows(new_data)
  }
  combined_data5 <- combined_data5 %>% rbind(changed_data)
}

combined_data5 %>% 
  filter(et_short_crop >0) %>%
  group_by(id) %>%
  ggplot(aes(x = sd,
             y = predict,
             color = id,
             group = id)) +
  geom_point() + geom_line()
ggplotly()
```


## lai_hv
```{r}
combined_data6 <- data.frame()
for (i in 1:length(id_list)) {
  id = id_list[i]
  data_id <- data_avg %>% filter(id == id_list[i])
  mean <- (data_sd %>% filter(id == id_list[i]))$lai_hv_mean
  sd <- (data_sd %>% filter(id == id_list[i]))$lai_hv_sd
  changed_data <- data.frame()
  for (j in -5:5) {
    new_values <- (j * sd) + mean
    data_id$lai_hv <- new_values
    predicted_values <- mean(predict(model, data_id)$predictions)
    
    new_data <-tibble(id = id_list[i],
                      sd = j,
                      predict = predicted_values)
    
    changed_data <- changed_data %>% bind_rows(new_data)
  }
  combined_data6 <- combined_data6 %>% rbind(changed_data)
}

combined_data6 %>% 
  group_by(id) %>%
  ggplot(aes(x = sd,
             y = predict,
             color = id,
             group = id)) +
  geom_point() + geom_line()
ggplotly()
```


## si10
```{r}
combined_data7 <- data.frame()
for (i in 1:length(id_list)) {
  id = id_list[i]
  data_id <- data_avg %>% filter(id == id_list[i])
  mean <- (data_sd %>% filter(id == id_list[i]))$si10_mean
  sd <- (data_sd %>% filter(id == id_list[i]))$si10_sd
  changed_data <- data.frame()
  for (j in -5:5) {
    new_values <- (j * sd) + mean
    data_id$si10 <- new_values
    predicted_values <- mean(predict(model, data_id)$predictions)
    
    new_data <-tibble(id = id_list[i],
                      sd = j,
                      predict = predicted_values,
                      si10 = new_values)
    
    changed_data <- changed_data %>% bind_rows(new_data)
  }
  combined_data7 <- combined_data7 %>% rbind(changed_data)
}

combined_data7 %>% 
  filter(si10 > 0 ) %>%
  group_by(id) %>%
  ggplot(aes(x = sd,
             y = predict,
             color = id,
             group = id)) +
  geom_point() + geom_line()
ggplotly()
```


## s0_pct
```{r}
combined_data8 <- data.frame()
for (i in 1:length(id_list)) {
  id = id_list[i]
  data_id <- data_avg %>% filter(id == id_list[i])
  mean <- (data_sd %>% filter(id == id_list[i]))$s0_pct_mean
  sd <- (data_sd %>% filter(id == id_list[i]))$s0_pct_sd
  changed_data <- data.frame()
  for (j in -5:5) {
    new_values <- (j * sd) + mean
    data_id$s0_pct <- new_values
    predicted_values <- mean(predict(model, data_id)$predictions)
    
    new_data <-tibble(id = id_list[i],
                      sd = j,
                      predict = predicted_values,
                      s0_pct = new_values)
    
    changed_data <- changed_data %>% bind_rows(new_data)
  }
  combined_data8 <- combined_data8 %>% rbind(changed_data)
}

combined_data8 %>% 
  filter(s0_pct > 0) %>%
  group_by(id) %>%
  ggplot(aes(x = sd,
             y = predict,
             color = id,
             group = id)) +
  geom_point() + geom_line()
ggplotly()
```

# max_temp
```{r}
data2 <- data %>% mutate(pred = predict(model, data)$predictions,
                         sd = "0")

data_sd1 <- data

# changing all the values
data_sd1 <- data.frame()
for (i in 1:length(id_list)) {
  data_id <- data %>% filter(id == id_list[i])
  mean <- (data_sd %>% filter(id == id_list[i]))$max_temp_mean
  sd <- (data_sd %>% filter(id == id_list[i]))$max_temp_sd

  data_changed <- data_id %>%
    mutate(max_temp = max_temp + sd)
  
  data_changed <- data_changed %>% bind_cols(pred = predict(model, data_changed)$predictions)
    
  data_sd1 <- data_sd1 %>% rbind(data_changed)
}

data_sd1 <- data_sd1 %>% mutate(sd = "+1")

data_sdm1 <- data.frame()
for (i in 1:length(id_list)) {
  data_id <- data %>% filter(id == id_list[i])
  mean <- (data_sd %>% filter(id == id_list[i]))$max_temp_mean
  sd <- (data_sd %>% filter(id == id_list[i]))$max_temp_sd

  data_changed <- data_id %>%
    mutate(max_temp = max_temp - sd)
  
  data_changed <- data_changed %>% bind_cols(pred = predict(model, data_changed)$predictions)
    
  data_sdm1 <- data_sdm1 %>% rbind(data_changed)
}

data_sdm1 <- data_sdm1 %>% mutate(sd = "-1")

data2 <- data2 %>% bind_rows(data_sd1, data_sdm1)


```

```{r}
data2 %>%
  ggplot(aes(x = max_temp, 
             y = pred,
             colour = sd)) +
  geom_point() +
  facet_grid(month ~ year, scales = "free") +
  ggtitle("Predicted values for changes in max_temp")
```

```{r}
data2 %>%
  mutate(sd = factor(sd, levels = c("-1", "0", "+1"))) %>%
  filter(id == 1) %>%
  ggplot(aes(x = sd,
             y = pred)) +
  geom_point() +
  facet_grid(month ~ year, scales = "free")
  
```

# daily_rain
```{r}
data3 <- data %>% mutate(pred = predict(model, data)$predictions,
                         sd = "0")

# changing all the values
data_sd1_rain <- data.frame()
for (i in 1:length(id_list)) {
  data_id <- data %>% filter(id == id_list[i])
  mean <- (data_sd %>% filter(id == id_list[i]))$daily_rain_mean
  sd <- (data_sd %>% filter(id == id_list[i]))$daily_rain_sd

  data_changed <- data_id %>%
    mutate(daily_rain = daily_rain + sd)
  
  data_changed <- data_changed %>% bind_cols(pred = predict(model, data_changed)$predictions)
    
  data_sd1_rain <- data_sd1_rain %>% rbind(data_changed)
}

data_sd1_rain <- data_sd1_rain %>% mutate(sd = "+1")

data_sdm1_rain <- data.frame()
for (i in 1:length(id_list)) {
  data_id <- data %>% filter(id == id_list[i])
  mean <- (data_sd %>% filter(id == id_list[i]))$daily_rain_mean
  sd <- (data_sd %>% filter(id == id_list[i]))$daily_rain_sd

  data_changed <- data_id %>%
    mutate(daily_rain = daily_rain - sd)
  
  data_changed <- data_changed %>% bind_cols(pred = predict(model, data_changed)$predictions)
    
  data_sdm1_rain <- data_sdm1_rain %>% rbind(data_changed)
}

data_sdm1_rain <- data_sdm1_rain %>% mutate(sd = "-1")

data3 <- data3 %>% bind_rows(data_sd1_rain, data_sdm1_rain)


```

```{r}
data3 %>%
  ggplot(aes(x = daily_rain, 
             y = pred,
             colour = sd)) +
  geom_point() +
  facet_grid(month ~ year, scales = "free") +
  ggtitle("Predicted values for changes in max_temp")
```

```{r}
data3 %>%
  mutate(sd = factor(sd, levels = c("-1", "0", "+1"))) %>%
  filter(id == 1) %>%
  ggplot(aes(x = sd,
             y = pred)) +
  geom_point() +
  facet_grid(month ~ year, scales = "free")
  
```

## changes on all values instead of average values
```{r}
combined_data9 <- data.frame()
for (i in 1:length(id_list)) {
  data_id <- data %>% filter(id == id_list[i])
  mean <- (data_sd %>% filter(id == id_list[i]))$max_temp_mean
  sd <- (data_sd %>% filter(id == id_list[i]))$max_temp_sd
  df <- data.frame()
  for (j in -5:5) {
    
    changed_data <- data_id %>% mutate(max_temp = max_temp + (j *sd))
  
  changed_data <- changed_data %>% bind_cols(pred = predict(model, changed_data)$predictions)
    
    predicted_values <- mean(changed_data$pred)
    
    new_data <-tibble(id = id_list[i],
                      sd = j,
                      predict = predicted_values,
                      max_temp = mean(changed_data$max_temp))
    
    df <- df %>% bind_rows(new_data)
  }
  combined_data9 <- combined_data9 %>% rbind(df)
}

combined_data9 %>% 
  filter(max_temp > 0) %>%
  group_by(id) %>%
  ggplot(aes(x = sd,
             y = predict,
             color = id,
             group = id)) +
  geom_point() + geom_line()
ggplotly()
```


```{r}
combined_data10 <- data.frame()
for (i in 1:length(id_list)) {
  data_id <- data %>% filter(id == id_list[i])
  mean <- (data_sd %>% filter(id == id_list[i]))$radiation_mean
  sd <- (data_sd %>% filter(id == id_list[i]))$radiation_sd
  df <- data.frame()
  for (j in -5:5) {
    
    changed_data <- data_id %>% mutate(radiation = radiation + (j *sd))
  
  changed_data <- changed_data %>% bind_cols(pred = predict(model, changed_data)$predictions)
    
    predicted_values <- mean(changed_data$pred)
    
    new_data <-tibble(id = id_list[i],
                      sd = j,
                      predict = predicted_values,
                      radiation = mean(changed_data$radiation))
    
    df <- df %>% bind_rows(new_data)
  }
  combined_data10 <- combined_data10 %>% rbind(df)
}

combined_data10 %>% 
  filter(radiation > 0) %>%
  group_by(id) %>%
  ggplot(aes(x = sd,
             y = predict,
             color = id,
             group = id)) +
  geom_point() + geom_line()
ggplotly()
```

```{r}
combined_data11 <- data.frame()
for (i in 1:length(id_list)) {
  data_id <- data %>% filter(id == id_list[i])
  mean <- (data_sd %>% filter(id == id_list[i]))$daily_rain_mean
  sd <- (data_sd %>% filter(id == id_list[i]))$daily_rain_sd
  df <- data.frame()
  for (j in -5:5) {
    
    changed_data <- data_id %>% mutate(daily_rain = daily_rain + (j *sd))
  
  changed_data <- changed_data %>% bind_cols(pred = predict(model, changed_data)$predictions)
    
    predicted_values <- mean(changed_data$pred)
    
    new_data <-tibble(id = id_list[i],
                      sd = j,
                      predict = predicted_values,
                      daily_rain = mean(changed_data$daily_rain))
    
    df <- df %>% bind_rows(new_data)
  }
  combined_data11 <- combined_data11 %>% rbind(df)
}

combined_data11 %>% 
  filter(daily_rain > 0) %>%
  group_by(id) %>%
  ggplot(aes(x = sd,
             y = predict,
             color = id,
             group = id)) +
  geom_point() + geom_line()
ggplotly()
```


```{r}
data_sd1 <- data
for (i in 1:length(id_list)) {
  mean <- (data_sd %>% filter(id == id_list[i]))$max_temp_mean
  sd <- (data_sd %>% filter(id == id_list[i]))$max_temp_sd
  data_sd1$max_temp[data_sd1$year == 2021 & data_sd1$month == 3 & data_sd1$id == id_list[i]] <- (data_sd1 %>% filter(id == id_list[i] & year == 2021 & month == 3))$max_temp + sd
}

data_sd1 <- 
```


```{r}
 (data_sd1 %>% filter(id == 1 & year == 2021 & month == 3))$max_temp 
```


```{r}
data %>%
  ggplot(aes(x = max_temp, 
             y = fire_count)) +
  geom_point() +
  facet_grid(year ~ month)
```

```{r}
data_predicted <- data %>% mutate( predictions = predict(model, data)$predictions)

data_predicted %>%
  ggplot(aes(x = max_temp, 
             y = predictions)) +
  geom_point() +
  facet_grid(year ~ month)
```

